name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run Component
        uses: cypress-io/github-action@v5
        with:
          component: true

      - name: Cypress run E2E
        uses: cypress-io/github-action@v5
        with:
          install: false
          start: npm start
          wait-on: 'http://localhost:3000'